version: '3'
services:
  app:
    build:
      args: 
        APP_DOCUMENT_ROOT: /var/www/html/legume/public
      context: ./build/mpapws
    image: iutlr-info-apache-symfony5-mpapws
    container_name: iutlr-info2-projet-mpapws
    ports:
      - 9999:80
    volumes:
      - ./legume:/var/www/html/legume 
    networks:
      - mpapws-network
  mysql:
    build:
      context: build/mysql
    image: iutlr-info-mysql-mpapws
    container_name: iutlr-info2-mysql-mpapws
    ports:
      - 3307:3306
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: db-mpapws
      MYSQL_USER: mpapws
      MYSQL_PASSWORD: mpapws
      MYSQL_ROOT_PASSWORD: mpapws
    networks:
      - mpapws-network
networks:
  mpapws-network:
    driver: bridge

